# frozen_string_literal: true

source 'https://rubygems.org/'

# ruby File.read('.ruby-version').strip

gem 'sinatra'

gem 'sinatra-cross_origin'

gem 'activerecord'

gem 'rake' 

gem 'pg' 

gem 'sinatra-activerecord'

gem 'bcrypt'

gem 'puma'

gem 'require_all'

# gem 'rubocop', '~> 1.46', require: false

group :development do
  gem 'faker'
  gem 'rerun'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'sqlite3'
end
